"use client";

import { useState } from "react";
import { toast } from "sonner";
import { useResetTutorial } from "../../components/dialogs/help-dialog";
import { Button } from "../../components/ui/button";
import { Select } from "../../components/ui/select";
import { useUpdateUser, useUserProfile } from "../../hooks/use-api";
import { Locale } from "../../lib/i18n";

export default function WelcomePage() {
  const { data } = useUserProfile();
  const updateLanguage = useUpdateUser();
  const [loading, setLoading] = useState(false);
  const [state, setState] = useState<"select-language" | "security" | "ready">(
    "select-language",
  );
  const { handleResetTutorial } = useResetTutorial();

  if (state === "select-language") {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-zinc-50 to-zinc-100 dark:from-zinc-900 dark:to-black p-4">
        <div className="w-full max-w-md space-y-8 rounded-2xl bg-white p-8 shadow-xl dark:bg-zinc-950">
          <h1>Bonjour {data?.name || "there"}!</h1>
          We'll start in a few seconds. Could you choose a language to continue
          ?
          <br />
          <br />
          <Select
            value={data?.language as Locale}
            onChange={async (value) => {
              setLoading(true);
              try {
                await updateLanguage.mutateAsync({ language: value });
              } catch (error) {
                console.error("Error saving language:", error);
                toast.error("An error occurred while saving your language.");
              } finally {
                setLoading(false);
              }
            }}
            options={[
              { label: "English", value: "en" },
              { label: "Français", value: "fr" },
              { label: "Español", value: "es" },
              { label: "Deutsch", value: "de" },
            ]}
          />
          <Button
            disabled={loading}
            className="mt-4"
            onClick={() => setState("security")}
          >
            Continue
          </Button>
        </div>
      </div>
    );
  }

  if (state === "security") {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-zinc-50 to-zinc-100 dark:from-zinc-900 dark:to-black p-4">
        <div className="w-full max-w-md space-y-8 rounded-2xl bg-white p-8 shadow-xl dark:bg-zinc-950">
          <h1>Security first</h1>
          We take your privacy seriously. All your data is encrypted end-to-end,
          which means <strong>only you can access it.</strong> We don't have the
          keys, not even for support.
          <br />
          <br />
          Here is your unique certificate, generated by your browser. Save it
          and send it to yourself by email. You'll need it to recover your data
          if you lose access to your account. You will also need it to use the
          app from another device. #TODO - create a check box for each points
          #TODO - The user can also decide not to use encryption, they can
          always enable it later.
          <br />
          <br />
          <Button
            disabled={loading}
            className="mt-4"
            onClick={() => setState("ready")}
          >
            All set
          </Button>
        </div>
      </div>
    );
  }

  if (state === "ready") {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-zinc-50 to-zinc-100 dark:from-zinc-900 dark:to-black p-4">
        <div className="w-full max-w-md space-y-8 rounded-2xl bg-white p-8 shadow-xl dark:bg-zinc-950">
          <h1>All set!</h1>
          You're all set to start transcribing. Click the button below to create
          your first transcription project.
          <br />
          <br />
          <Button
            disabled={loading}
            className="mt-4"
            onClick={async () => {
              setLoading(true);
              try {
                await updateLanguage.mutateAsync({ isWelcomeCompleted: true });
                await handleResetTutorial(data?.language || "en");
              } catch (err) {
                console.error("Error completing welcome:", err);
                toast.error(
                  "An error occurred while setting up your account. Please try again.",
                );
              } finally {
                setLoading(false);
              }
            }}
          >
            Run the tutorial
          </Button>
        </div>
      </div>
    );
  }

  return null;
}
