"use client";

import type { CodingDTO } from "@/lib/codebooks/coding";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { fetchGateway } from "./fetch";

/**
 * The codings of one document: which passages carry which codes, and from whom.
 *
 * Nothing here is encrypted. A coding is two opaque uuids and an author — the labels
 * live inside the codebook's encrypted content and the passage inside the transcript,
 * so there is nothing to decrypt on this side (see lib/codebooks/coding.ts).
 */
export function useCodings(transcriptionId: string | undefined) {
  return useQuery({
    queryKey: ["codings", transcriptionId],
    enabled: !!transcriptionId,
    queryFn: async (): Promise<CodingDTO[]> => {
      const response = await fetchGateway(
        `/api/transcriptions/${transcriptionId}/codings`,
      );
      if (!response.ok) throw new Error("Failed to fetch codings");
      const { codings } = (await response.json()) as { codings: CodingDTO[] };
      return codings;
    },
  });
}

export type NewCoding = {
  /** Generated by the caller: the mark carries it before the row exists. */
  id: string;
  codebookId: string;
  codeId: string;
};

/**
 * Apply a code to the passage anchored by `id`.
 *
 * The response is written STRAIGHT INTO the cache rather than invalidating it. Coding
 * is a rapid-fire action — a code every second or two through a whole interview — and
 * the server has just told us exactly what it stored, so refetching the document's
 * whole coding list after each one is a round trip whose answer we already hold.
 */
export function useAddCoding(transcriptionId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (coding: NewCoding) => {
      const response = await fetchGateway(
        `/api/transcriptions/${transcriptionId}/codings`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(coding),
        },
      );
      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error || "Failed to add coding");
      }
      return (await response.json()) as { coding: CodingDTO };
    },
    onSuccess: ({ coding }) => {
      queryClient.setQueryData<CodingDTO[]>(
        ["codings", transcriptionId],
        (current) =>
          current
            ? // Guard against a concurrent refetch having already brought it in.
              current.some((c) => c.id === coding.id)
              ? current
              : [...current, coding]
            : [coding],
      );
    },
  });
}

/**
 * Remove one coding (author only, enforced server-side). Dropped from the cache
 * directly, for the same reason {@link useAddCoding} writes into it.
 */
export function useDeleteCoding(transcriptionId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (codingId: string) => {
      const response = await fetchGateway(
        `/api/transcriptions/${transcriptionId}/codings/${codingId}`,
        { method: "DELETE" },
      );
      if (!response.ok) throw new Error("Failed to delete coding");
      return response.json();
    },
    onSuccess: (_data, codingId) => {
      queryClient.setQueryData<CodingDTO[]>(
        ["codings", transcriptionId],
        (current) => current?.filter((c) => c.id !== codingId) ?? [],
      );
    },
  });
}
