"use client";

import type { CodingDTO } from "@/lib/codebooks/coding";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { fetchGateway } from "./fetch";

/**
 * The codings of one document: which passages carry which codes, and from whom.
 *
 * Nothing here is encrypted. A coding is two opaque uuids and an author — the labels
 * live inside the codebook's encrypted content and the passage inside the transcript,
 * so there is nothing to decrypt on this side (see lib/codebooks/coding.ts).
 */
export function useCodings(transcriptionId: string | undefined) {
  return useQuery({
    queryKey: ["codings", transcriptionId],
    enabled: !!transcriptionId,
    queryFn: async (): Promise<CodingDTO[]> => {
      const response = await fetchGateway(
        `/api/transcriptions/${transcriptionId}/codings`,
      );
      if (!response.ok) throw new Error("Failed to fetch codings");
      const { codings } = (await response.json()) as { codings: CodingDTO[] };
      return codings;
    },
  });
}

export type NewCoding = {
  /** Generated by the caller: the mark carries it before the row exists. */
  id: string;
  codebookId: string;
  codeId: string;
};

/**
 * Apply a code to the passage anchored by `id`.
 *
 * The mark is written into the document first (that is what the researcher sees), so
 * this is optimistic by construction: the new coding is pushed into the cache
 * immediately and reconciled when the request lands. A failure rolls the cache back —
 * the caller is responsible for taking the mark out again.
 */
export function useAddCoding(transcriptionId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (coding: NewCoding) => {
      const response = await fetchGateway(
        `/api/transcriptions/${transcriptionId}/codings`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(coding),
        },
      );
      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error || "Failed to add coding");
      }
      return (await response.json()) as { coding: CodingDTO };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ["codings", transcriptionId],
      });
    },
  });
}

/** Remove one coding (author only, enforced server-side). */
export function useDeleteCoding(transcriptionId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (codingId: string) => {
      const response = await fetchGateway(
        `/api/transcriptions/${transcriptionId}/codings/${codingId}`,
        { method: "DELETE" },
      );
      if (!response.ok) throw new Error("Failed to delete coding");
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ["codings", transcriptionId],
      });
    },
  });
}
