/**
 * Socket.IO Authentication Helper
 * Handles authentication using JWT tokens
 * Works for all auth modes (local, LDAP, Auth0)
 */

import { Socket } from "socket.io";
import { verifySocketToken } from "../auth/utils";
import { prisma } from "../prisma";

export interface SocketAuthResult {
  userId: string;
  email: string;
  name?: string;
}

/**
 * Main authentication function for Socket.IO connections
 * Verifies JWT socket tokens generated by /api/user/socket-token
 *
 * Works universally for all auth modes:
 * - Local users (with password hash)
 * - LDAP users (authenticated via LDAP but stored in local DB)
 * - Auth0 users (authenticated via Auth0 but stored in local DB)
 *
 * All users get the same JWT socket token format.
 */
export async function verifySocketAuth(
  socket: Socket,
): Promise<SocketAuthResult | null> {
  try {
    // Get token from auth object (client should send it when connecting)
    const token = socket.handshake.auth?.token;

    if (!token) {
      console.error("[Socket Auth] No token provided in socket handshake");
      return null;
    }

    // Verify JWT socket token
    const userId = await verifySocketToken(token);
    if (!userId) {
      console.error("[Socket Auth] Invalid or expired socket token");
      return null;
    }

    // Verify user exists in database
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        email: true,
        name: true,
      },
    });

    if (!user) {
      console.error("[Socket Auth] User not found in database:", userId);
      return null;
    }

    return {
      userId: user.id,
      email: user.email,
      name: user.name || undefined,
    };
  } catch (error) {
    console.error("[Socket Auth] Verification error:", error);
    return null;
  }
}
