/**
 * Socket.IO Authentication Helper
 * Handles authentication using JWT tokens
 * Works for all auth modes (local, LDAP, Auth0)
 */

import { Socket } from "socket.io";
import { verifySocketTokenClaims } from "../auth/utils";

export interface SocketAuthResult {
  userId: string;
  email?: string;
  name?: string;
}

/**
 * Main authentication function for Socket.IO connections
 * Verifies JWT socket tokens generated by /api/user
 *
 * Works universally for all auth modes:
 * - Local users (with password hash)
 * - LDAP users (authenticated via LDAP but stored in local DB)
 * - Auth0 users (authenticated via Auth0 but stored in local DB)
 *
 * All users get the same JWT socket token format.
 *
 * No database round-trip: the socket server runs in the custom Node server, which
 * has no working Prisma client. It does not need one — the token is signed with
 * the session secret and was minted by an API route that had just authenticated
 * the user, so verifying the signature IS the check. The account it names existed
 * moments ago (tokens last 24h) and, more to the point, existing is not what
 * grants access to anything: every room join is authorized separately by a room
 * grant (see room-grant.ts).
 */
export async function verifySocketAuth(
  socket: Socket,
): Promise<SocketAuthResult | null> {
  try {
    // Get token from auth object (client should send it when connecting)
    const token = socket.handshake.auth?.token;

    if (!token) {
      console.error("[Socket Auth] No token provided in socket handshake");
      return null;
    }

    // Verify JWT socket token
    const claims = await verifySocketTokenClaims(token);
    if (!claims) {
      console.error("[Socket Auth] Invalid or expired socket token");
      return null;
    }

    return {
      userId: claims.userId,
      email: claims.email,
      name: claims.name,
    };
  } catch (error) {
    console.error("[Socket Auth] Verification error:", error);
    return null;
  }
}
